# Generated by Django 4.2.14 on 2024-08-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("message", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
